### ISSUE TITLE
Issues relating to rc2

### ISSUE THREAD

**Issue by sparkblaze** [rokett/ldap-query#1]
- On first run, the sample config.toml file is never created (what's wrong with Yaml?)

```
{"build":"60acec3f318284993997be5384ad95377cfadee0","error":"FindFirstFile C:\\Test/config.toml: The system cannot find the file specified.","function":"loadConfig","level":"error","msg":"the configuration file does not exist; creating template config file","time":"2020-01-21T16:31:56Z","version":"1.0.0-rc.2"}

{"build":"60acec3f318284993997be5384ad95377cfadee0","error":"FindFirstFile C:\\templates\\config.example.toml: The system cannot find the path specified.","function":"loadConfig","level":"error","msg":"unable to load ../../templates/config.example.toml","time":"2020-01-21T16:31:56Z","version":"1.0.0-rc.2"}
```

- It doesn't look possible to query multiple domains?
- `allowed_sources` doesn't appear to work - I get a not allowed thrown back
```
{
  "message": "192.168.136.6 is not allowed to query; check the config"
}
```

**Comment by rokett** [comment]
re TOML vs YAML - No specific reason other than I'd used TOML in a previous project and had a bunch of code ready to go which I could just port over.   TOML is more forgiving about whitespace than YAML, but other than that they're pretty much interchangeable.

Looking into the config template not being created.

It's not possible to query multiple domains; my thinking here is to run additional services for other domains, although I could likely make it query multiple domains if you felt that was beneficial over running multiple services?

Presumably you created the config file manually to determine that the source was not allowed?  Would need to check through the config to find out what is going on there if so.

**Comment by rokett** [comment]
Following our changes I think the only outstanding issue is the config file not being created.  I'll take a closer look at that and push all the changes later.

**Comment by rokett** [comment]
RC3 moves the config to flags and does away with the config file.

**Comment by rokett** [comment]
@sparkblaze Just a note that v1.0.0 has now been released.  Docker image is at https://hub.docker.com/r/rokett/ldap-query if you want it.
